---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
  namespace: development
  labels:
    app: url-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-service
  template:
    metadata:
      labels:
        app: url-service
    spec:
      containers:
        - image: xcoulon/go-url-shortener:0.1.0
          name: go-url-shortener
          env:
            - name: POSTGRES_HOST
              value: 10.244.0. # todo: Need to change to DNS
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: url_shortener_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          ports:
            - containerPort: 8080