---
- name: install nginx and start service
  hosts: server
  become: true
  tasks:

    - name: install nginx
      apt: name=nginx state=present

    - name: start service
      service: name=nginx state=restarted

# write command to Uninstall nginx
