---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-deployment
  namespace: development
  labels:
    name: pod-info
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pod-info
  template:
    metadata:
      labels:
        name: pod-info
    spec:
      containers:
        - name: pod-info-container
          image: nginx:alpine
          ports:
            - containerPort: 80